---
title: "ANA 515 Visual Activity Week 5"
author: "Sravanivennavaram"
date: '2021'
output:
  html_document:
    df_print: paged
  theme:
    bootswatch: cerulean
    df_print: paged
  word_document: null
---

Reading the Gun-Deaths Dataset

```{r, echo = FALSE}
url <- 'https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv'
gun_deaths <- read.csv(url)
```


Histogram showing the distribution of age of the victims of gun shots.

```{r, echo = FALSE}
library(ggplot2)
ggplot(gun_deaths, aes(x=age)) + 
  geom_histogram(color="yellow", fill="blue", bins = 20) +
  labs(title="Age Distribution Histogram")
```


Scatter-plot: Number of gun deaths (y-axis) by age (x-axis) with or without police involvement (color)

```{r, echo = FALSE}
library(dplyr)
gun_deaths$police <- as.factor(gun_deaths$police)
gun_deaths %>%
  group_by(age, police) %>%
  tally() %>%
  ggplot(aes(x = age, y = n, color = police)) +
  geom_point() +
  geom_line() +
  labs(title = 'Gun Deaths by age with/without police involvement', y="Number of Gun Deaths")
```



